version: '2'
services:
  consul:
    image: gliderlabs/consul-server
    ports:
      - 8500
    command: "-bootstrap -bind 0.0.0.0 -client 0.0.0.0 -ui"
    dns_search: ""
    labels:
      - "SERVICE_8500_NAME=consul"
      - "SERVICE_8500_TAGS=load-balance"
    restart: always

  registrator:
    image: gliderlabs/registrator:latest
    command: -ip 192.168.99.100 consul://consul:8500
    dns_search: ""
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    restart: always
    depends_on:
      - consul

  lb:
    build: .
    dns_search: ""
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - consul
